nflp_site/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
  path('', views.Home.as_view(), name='home'),
]

nflp_site/nflp_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('teams/', include('teams.urls', namespace='teams')),
    path('players/', include('players.urls', namespace='players')),
    path('stadiums/', include('stadiums.urls', namespace='stadiums')),
    path('admin/', admin.site.urls),
]

nflp_site/players/urls.py
from django.urls import path
from . import views

app_name = 'players'
urlpatterns = [
  path('', views.ListPlayers.as_view(), name='list-players'),
  path('<int:pk>', views.DetailPlayer.as_view(), name='detail-player'),
]

nflp_site/stadiums/urls.py
from django.urls import path
from . import views

app_name = 'stadiums'
urlpatterns = [
  path('', views.ListStadiums.as_view(), name='list-stadiums'),
  path('<int:pk>', views.DetailStadium.as_view(), name='detail-stadium'),
]

nflp_site/teams/urls.py
from django.urls import path
from . import views

app_name = 'teams'
urlpatterns = [
  path('', views.ListTeams.as_view(), name='list-teams'),
  path('<int:pk>', views.DetailTeam.as_view(), name='detail-team'),
]

nflp_site/home/models.py
from django.db import models

# Create your models here.

nflp_site/players/models.py
from django.db import models
from teams.models import Team

class Player(models.Model):
  first_name = models.CharField(max_length=250)
  last_name = models.CharField(max_length=250)
  team = models.ForeignKey(Team, on_delete=models.CASCADE, default=1)
  position = models.CharField(max_length=100)
  timestamp = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return f'{self.first_name} {self.last_name}'

nflp_site/stadiums/models.py
from django.db import models

class Stadium(models.Model):
  name = models.CharField(max_length=150)
  address = models.CharField(max_length=250)

  def __str__(self):
    return f'{self.name}'

nflp_site/teams/models.py
from django.db import models
from stadiums.models import Stadium

class Team(models.Model):
  name = models.CharField(max_length=150)
  stadium = models.OneToOneField(Stadium, on_delete=models.CASCADE, null=True)
  location = models.CharField(max_length=250)
  timestamp = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.name

nflp_site/home/views.py
from django.shortcuts import render
from django.views import generic

class Home(generic.TemplateView):
  template_name = 'home/home.html'

nflp_site/players/views.py
from django.shortcuts import get_object_or_404
from django.views import generic
from .models import Player

class ListPlayers(generic.ListView):
  template_name = 'players/list_players.html'
  model = Player
  context_object_name = 'players'

  def get_queryset(self):
    query = self.request.GET.get('search', '')
    queryForPos = self.request.GET.get('searchForPosition', '')
    
    if query:
      print('hola')
      object_list = Player.objects.filter(team__name__icontains=query)
    elif queryForPos:
      object_list = Player.objects.filter(position__icontains=queryForPos)
    else:
      object_list = Player.objects.all()
    return object_list

class DetailPlayer(generic.DeleteView):
  template_name = 'players/detail_player.html'
  model = Player
  context_object_name = 'player'

nflp_site/stadiums/views.py
from django.shortcuts import render
from django.views import generic
from .models import Stadium

class ListStadiums(generic.ListView):
  template_name = 'stadiums/list_stadiums.html'
  model = Stadium
  context_object_name = 'stadiums'

class DetailStadium(generic.DeleteView):
  template_name = 'stadiums/detail_stadium.html'
  model = Stadium
  context_object_name = 'stadium'

nflp_site/teams/views.py
from django.shortcuts import render
from django.views import generic
from .models import Team

class ListTeams(generic.ListView):
  template_name = 'teams/list_teams.html'
  model = Team
  context_object_name = 'teams'

class DetailTeam(generic.DeleteView):
  template_name = 'teams/detail_team.html'
  model = Team
  context_object_name = 'team'

nflp_site/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %} | Official Site of the National Football League Parra</title>
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'styles/custom.css' %}">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="{% url 'home:home' %}">NFLP</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'home:home' %}">Home</a>
        <a class="nav-item nav-link" href="{% url 'teams:list-teams' %}">Teams</a>
        <a class="nav-item nav-link" href="{% url 'players:list-players' %}">Players</a>
        <a class="nav-item nav-link" href="{% url 'stadiums:list-stadiums' %}">Stadiums</a>
      </div>
    </div>
  </nav>
  
  <div class="container mt-5">
    {% block content %}{% endblock %}
  </div>

  <script src="{% static 'jquery-3.4.1.min.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

nflp_site/templates/home/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
  <div class="text-center">
    <h1>Welcome to NFLP</h1>
  </div>
{% endblock %}

nflp_site/templates/players/detail_player.html
{% extends 'base.html' %}

{% block title %}{{ player.first_name }} {{ player.last_name }}{% endblock %}

{% block content %}
  <a class="btn btn-primary" href="{% url 'players:list-players' %}">Back to players</a>
  <div class="card mt-2">
    <div class="card-header">
      Player
    </div>
    <div class="card-body">
      <h5>Name: {{ player.first_name }} {{ player.last_name }}</h5>
      <p>
        <!-- Team: {{ player.team }} -->
        Position: {{ player.position }}
      </p>
    </div>
  </div>
{% endblock %}

nflp_site/templates/players/list_players.html
{% extends 'base.html' %}

{% block title %}Player List{% endblock %}

{% block content %}
  {% if not players %}
    <div class="text-center">
      <h3>No players yet</h3>
      <a class="btn" href="{% url 'home:home' %}">Back to home</a>
    </div>
  {% else %}
    <form class="form-inline my-2 my-lg-0" method="GET">
      <input class="form-control mr-sm-2" type="search" name="search" placeholder="Search for team" aria-label="SearchForTeam">
      <button class="btn btn-primary my-2 my-sm-0" type="submit">Search for team</button>
    </form>
    <br />
    <form class="form-inline my-2 my-lg-0" method="GET">
      <input class="form-control mr-sm-2" type="search" name="searchForPosition" placeholder="Search for position" aria-label="SearchForPosition">
      <button class="btn btn-primary my-2 my-sm-0" type="submit">Search for position</button>
    </form>
    <br />
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">First name</th>
          <th scope="col">Last name</th>
          <th scope="col">Team</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {% for player in players %}
          <tr>
            <td>{{ player.first_name }}</td>
            <td>{{ player.last_name }}</td>
            <td>{{ player.team }}</td>
            <td>
              <a class="btn btn-primary" href="{% url 'players:detail-player' player.id %}">Detail</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endif %}
{% endblock %}

nflp_site/templates/stadiums/detail_stadium.html
{% extends 'base.html' %}

{% block title %}{{ stadium.name }}{% endblock %}

{% block content %}
  <a class="btn btn-primary" href="{% url 'stadiums:list-stadiums' %}">Back to stadiums</a>
  <div class="card mt-2">
    <div class="card-header">
      Stadium
    </div>
    <div class="card-body">
      <p>
        Name: {{ stadium.name }} <br />
        <!-- Team: {{ stadium.team }} -->
        Address: {{ stadium.address }}
      </p>
    </div>
  </div>
{% endblock %}

nflp_site/templates/stadiums/list_stadiums.html
{% extends 'base.html' %}

{% block title %}Stadium List{% endblock %}

{% block content %}
  {% if not stadiums %}
    <div class="text-center">
      <h3>No stadiums yet</h3>
      <a class="btn" href="{% url 'home:home' %}">Back to home</a>
    </div>
  {% else %}
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Stadium name</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {% for stadium in stadiums %}
          <tr>
            <td>{{ stadium.name }}</td>
            <td>
              <a class="btn btn-primary" href="{% url 'stadiums:detail-stadium' stadium.id %}">Detail</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endif %}
{% endblock %}

nflp_site/templates/teams/detail_team.html
{% extends 'base.html' %}

{% block title %}{{ team.name }}{% endblock %}

{% block content %}
  <a class="btn btn-primary" href="{% url 'teams:list-teams' %}">Back to teams</a>
  <div class="card mt-2">
    <div class="card-header">
      Team
    </div>
    <div class="card-body">
      <h5>Name: {{ team.name }}</h5>
      <p>
        <!-- Stadium: {{ player.team }} -->
        Location: {{ team.location }}
      </p>
    </div>
  </div>
{% endblock %}

nflp_site/templates/teams/list_teams.html
{% extends 'base.html' %}

{% block title %}List of teams{% endblock %}

{% block content %}
  {% if not teams %}
    <div class="text-center">
      <h3>No teams yet</h3>
      <a class="btn" href="{% url 'home:home' %}">Back to home</a>
    </div>
  {% else %}
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Team name</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {% for team in teams %}
          <tr>
            <td>{{ team.name }}</td>
            <td>
              <a class="btn btn-primary" href="{% url 'teams:detail-team' team.id %}">Detail</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endif %}
{% endblock %}